# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_schedule', '0003_auto_20170717_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotkind',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
    ]
