# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
