# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalbase',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
    ]
