# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_proposals', '0002_auto_20170717_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalspeaker',
            options={'ordering': ['-order'], 'verbose_name': 'Addtional speaker', 'verbose_name_plural': 'Additional speakers'},
        ),
        migrations.AddField(
            model_name='additionalspeaker',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
