# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_sponsorship', '0002_auto_20160517_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='content_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('listing_text_pt-br', 'Listing Text (Portugu\xeas)'), ('listing_text_en', 'Listing Text (English)')], default='simple', max_length=20, verbose_name='content type'),
        ),
    ]
